### ISSUE TITLE
How to use 7.1 features

### ISSUE THREAD

**Issue by asgerhallas** [bridgedotnet/CLI#24]
I get the following exception when running bridge build on a file that contains 7.1 features:

> Bridge.NET Compiler error: exception level: 0 - C# Compilation Failed
>         Program.cs(84,45): CS8314: An expression of type 'TSubject' cannot be handled by a pattern of type 'T' in C# 7.0. Please use language version 7.1 or greater.

The same c# file works flawlessly on Deck.NET. 

I am using bridge-cli 17.3.0. How do I use the newer language versions?

**Comment by fabriciomurta** [comment]
We are already at 17.9.0, so this bug should be long gone. Please ping us if otherwise!
